---
# tasks file for editor-vim
- name: Makes sure autoload directory exists
  file:
      path: ~/.vim/autoload
      state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Make sure configuration directory exists.
  file:
      path: "{{ editor_vim_configdir }}"
      state: directory

- name: Make sure data directory exists.
  file:
      path: "{{ editor_vim_datadir }}"
      state: directory

- name: vimrc
  template:
      src: "{{ editor_vim_template_vimrc }}"
      dest: "{{ editor_vim_configdir }}/vimrc.vim"
